services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_parnaa
    restart: unless-stopped
    ports:
      - "9100:9000" # S3 API
      - "9090:9090" # Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123123
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9090"
    networks:
      - nft_marketplace_network

volumes:
  minio_data:
  minio_config:

networks:
  nft_marketplace_network:
    external: true
